# Generated by Django 3.0.5 on 2020-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='name',
            field=models.CharField(default='no message', max_length=20),
            preserve_default=False,
        ),
    ]
